### PR TITLE
msm8916-common: Drop init.qcom.ril.sh and use more subtle way to start ril-daemon2

### PR DESCRIPTION
**Pull request by Akianonymus**

### CODE REVIEW

**Comment by Akianonymus** [comment]
Tested on harpia and merlin

**Comment by sultanqasim** [comment]
Don't forget to actually delete init.qcom.ril.sh ;)

**Comment by Akianonymus** [comment]
aah, i forgot, lemme force push

**Comment by Akianonymus** [comment]
Done

**Pull request merged**
