### PR TITLE
Various updates and fixes

### PR DESCRIPTION
**Pull request by Akianonymus**

### CODE REVIEW

**Comment by Akianonymus** [comment]
The last commit is a blob update, i can't create a pr to your vendor repo as it's currently wip
So i am going to link the commits

This is for the last commit
I/ServiceManager( 663): Waiting for service vendor.qcom.PeripheralManager...

W/ServiceManager( 663): Service vendor.qcom.PeripheralManager didn't start. Returning NULL

E/PerMgrLib( 663): modem get service fail

E/PerMgrLib(  663): QCRIL failed to register for modem

https://github.com/Harpia-development/vendor_motorola/commit/c6a6b14088e665c142bb963cb8cb145da06dbfce

The fixes renderscript hal ( just the adreno blob from that commit )
E/RenderScript(2582): Failed loading RS driver: dlopen failed: library "libLLVM.so" not found

E/RenderScript(2582): Failed to load runtime libRSDriver_adreno.so, loading default

https://github.com/Harpia-development/vendor_motorola/commit/8d635fa22043df37cce5e21a4d6faebf653fa9db

**Comment by sultanqasim** [comment]
Thanks, I will work through these changes as I get time

**Comment by Akianonymus** [comment]
Also, i have another issue here

We have stml0xx driver in common tree, but it doesn't works for harpia, so it throws errors before booting resulting in logspam.

# Offtopic

Can i contact you on hangouts ?
For more fixes and stuffs

If you allow

**Comment by sultanqasim** [comment]
Sure, you know my hangouts email, right? It's my github username @ gmail.com

**Comment by Akianonymus** [comment]
Thx for the confirmation, yes i know, Asim already told me.

**Pull request merged**
