### PR TITLE
Andy's things 

### PR DESCRIPTION
**Pull request by ericfrs**

### CODE REVIEW

**Comment by Akianonymus** [comment]
may i know why you are removing c2d flag ?

**Comment by adithya2306** [comment]
well msm8916 uses C2D so its not supposed to be removed and with that flag present, copybit should be built and `debug.composition.type` prop should be set to `c2d`

**Comment by ericfrs** [comment]
Because msm8916 don't need copybit.. mdp can make all the ui transformation without any problem or issue

**Comment by Akianonymus** [comment]
I don't know if mdp will work or not, but even stock uses c2d composition.

**Comment by ericfrs** [comment]
Don't needed here.

**Comment by Akianonymus** [comment]
So, if we disable c2d, it will use mdp ?

**Comment by adithya2306** [comment]
> Because msm8916 don't need copybit.. mdp can make all the ui transformation without any problem or issue

https://github.com/LineageOS/android_hardware_qcom_display/blob/0570d12f6ffd7760bc1e4984d8225b5078c9e2c0/libqdutils/comptype.h#L66
"gpu" is the default composition type so even if you need to keep mdp you need to set the prop accordingly.

**Pull request closed without merging**
